--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/usy4/XboxProfile
build-by-default: true
branches:
- main
projects:
  XboxProfile:
    path: ""
    icon: "xbox.png"
    libs:
      - src: Vecnavium/FormsUI/FormsUI
        version: ^1.0.0
    - src: "CortexPE/Commando/Commando"
      branch: "PM4"
      version: ^3.0.0
...
